[versions]
agp = "8.12.3"
coil = "2.7.0"
exoplayer = "2.19.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
leanback = "1.0.0"
glide = "4.11.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

